### PR TITLE
🚀  Add dark and light support

### PR DESCRIPTION
**Pull request by alexanderwassbjer**
Here is the dark and light theme support.
- Added theme selector on account settings page.
- Fixed all style where light mode was not working.
- Ability to change between "system", "dark" and "light"

Screenshots:

image
image
image

### CODE REVIEW

**Comment by alexanderwassbjer** [comment]
@KMKoushik 😃

**Comment by alexanderwassbjer** [comment]
Question: Should the defaultTheme be system or dark? Please tell me your thoughts :)

**Comment by KMKoushik** [comment]
hey @alexanderwassbjer default should be dark imho, may be we can change to system when we are confident!

think this will also go to v2

**Comment by alexanderwassbjer** [comment]
> hey @alexanderwassbjer default should be dark imho, may be we can change to system when we are confident!
> 
> 
> 
> think this will also go to v2

Okay! Then I change to default dark for now

**Comment by alexanderwassbjer** [comment]
@alexanderwassbjer
Some other ideas for improvement:
- Encrypt the cache for the transactions.
- Add multiple bank accounts for different providers.

**Comment by alexanderwassbjer** [comment]
@KMKoushik Is there anything that you miss in this PR? :)

**Comment by KMKoushik** [comment]
this is good, i'll merge this in v2

**Review by KMKoushik — APPROVED** [review]

**Pull request merged**
