### PR TITLE
Documentation changes for local setup

### PR DESCRIPTION
**Pull request by anantraghuvanshi**
#16 fixes

### CODE REVIEW

**Review by KMKoushik — CHANGES_REQUESTED** [review]
Thank you so much for the PR. 

Only comment: Instead of the image, can put in the env name, why it's used and where to set it up.

Example:


R2 related env is for cloudflare R2 used to upload and can be set up [here](https://www.cloudflare.com/en-au/developer-platform/r2/)

**Comment by anantraghuvanshi** [comment]
@KMKoushik Thanks for the review. I have done the required changes. Kindly have a look and let me know any further changes are required.

**Review by anantraghuvanshi — COMMENTED** [review]
Required changes done!

**Review by KMKoushik — APPROVED** [review]

**Comment by KMKoushik** [comment]
LGMT. Thanks for the PR

**Pull request merged**
